### ISSUE TITLE
Change license to GPLv2+ or something more permissive

### ISSUE THREAD

**Issue by zx2c4** [armfazh/rfc7748_precomputed#2]
I'd like to use this in [WireGuard](https://www.wireguard.com/papers/wireguard.pdf), and by extension, in the Linux kernel. I've already imported it and gotten it ready for the kernel's environment, as well as reducing input points mod 2^255-19 and accounting for the various different CPU flags at runtime. However, right now it [lives in this unhappy branch](https://git.zx2c4.com/WireGuard/tree/src/crypto/curve25519-x86_64.h?h=jd/curve-precomp), which I can't yet merge to master, because this project appears to be LGPLv3+, whereas the kernel requires GPLv2.

Would you consider re-licensing this project to something compatible with GPLv2? This would include things like:

- GPLv2 itself.
- GPLv2+
- LGPLv2+
- GPLv2 and GPLv3
- LGPLv2 and LGPLv3
- BSD
- MIT
- Public domain
- Many other good candidates

Doing so will get this code some real world usage and deployment.

**Comment by tarcieri** [comment]
I would appreciate this as well, as I have shipped this code in the [x25519 RubyGem](https://github.com/crypto-rb/x25519)
